version: '3'

services:
  tccfront:
    container_name: tcc-frontend
    image: tcc-frontend
    depends_on:
      - tccback
    ports:
      - "20000:80"
    networks:
      - tcc-network

  tccback:
    container_name: tcc-backend
    image: tcc-backend
    build:
      context: ./TCC-Back
    ports:
      - "20001:80"
    networks:
      - tcc-network

networks: 
  tcc-network:
    driver: bridge