insert into Risco(TipoRiscoID, DescricaoRisco)
values(1,'Infiltração na barragem')
insert into Risco(TipoRiscoID, DescricaoRisco)
values(2,'Sensores de vídeo parados')
insert into Risco(TipoRiscoID, DescricaoRisco)
values(2,'Sensor A permanece parado')
insert into Risco(TipoRiscoID, DescricaoRisco)
values(1,'Sirene quebrada')
insert into Risco(TipoRiscoID, DescricaoRisco)
values(2,'Teste Risco')

insert into TipoRisco(NomeTipoRisco, Criticidade, LocalTipoRisco)
values('Tipo Risco 4', 'Criticidade 4', 'Local 4' )
insert into TipoRisco(NomeTipoRisco, Criticidade, LocalTipoRisco)
values('Tipo Risco 5', 'Criticidade 5', 'Local 5' )